import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { APP_STARTUP_IMAGES } from './app-splash';

// The list is generated by scripts/app-icons/generate.mjs together with the
// files it names; a stale list would make iOS show a blank launch screen.
describe('student app startup images', () => {
  it('names a file that exists for every device', () => {
    expect(APP_STARTUP_IMAGES.length).toBeGreaterThan(10);
    for (const img of APP_STARTUP_IMAGES) {
      expect(existsSync(join(process.cwd(), 'public', img.url)), img.url).toBe(true);
      expect(img.media).toMatch(/device-width: \d+px.*device-height: \d+px.*-webkit-device-pixel-ratio: [23].*portrait/);
    }
  });

  it('matches each file name to its media query dimensions', () => {
    for (const img of APP_STARTUP_IMAGES) {
      const [, w, h] = img.url.match(/app-(\d+)x(\d+)\.png$/) ?? [];
      const dw = Number(img.media.match(/device-width: (\d+)px/)?.[1]);
      const dh = Number(img.media.match(/device-height: (\d+)px/)?.[1]);
      const dpr = Number(img.media.match(/pixel-ratio: (\d)/)?.[1]);
      expect(Number(w)).toBe(dw * dpr);
      expect(Number(h)).toBe(dh * dpr);
    }
  });
});

describe('student app icons', () => {
  it('ships every icon the manifest and layout point at', () => {
    for (const f of ['app-180.png', 'app-192.png', 'app-512.png', 'app-maskable-512.png']) {
      expect(existsSync(join(process.cwd(), 'public', 'icons', f)), f).toBe(true);
    }
  });
});
