// GENERATED by scripts/app-icons/generate.mjs — do not edit by hand.
// iOS shows one of these behind the student app while it launches from the
// Home Screen; Safari picks the first media query that matches the device.
export type StartupImage = { url: string; media: string };

export const APP_STARTUP_IMAGES: StartupImage[] = [
  // iPhone 16 Pro Max / 17 Pro Max
  { url: '/splash/app-1320x2868.png', media: 'screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 16 Pro / 17 / 17 Pro
  { url: '/splash/app-1206x2622.png', media: 'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Air
  { url: '/splash/app-1260x2736.png', media: 'screen and (device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro Max / 15 Pro Max / 15 Plus / 16 Plus
  { url: '/splash/app-1290x2796.png', media: 'screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro / 15 / 15 Pro / 16
  { url: '/splash/app-1179x2556.png', media: 'screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12 Pro Max / 13 Pro Max / 14 Plus
  { url: '/splash/app-1284x2778.png', media: 'screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12 / 13 / 14
  { url: '/splash/app-1170x2532.png', media: 'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone X / XS / 11 Pro / 12 mini / 13 mini
  { url: '/splash/app-1125x2436.png', media: 'screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone XS Max / 11 Pro Max
  { url: '/splash/app-1242x2688.png', media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone XR / 11
  { url: '/splash/app-828x1792.png', media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone 6+ / 7+ / 8+
  { url: '/splash/app-1242x2208.png', media: 'screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 6 / 7 / 8 / SE 2 / SE 3
  { url: '/splash/app-750x1334.png', media: 'screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 13 (M4)
  { url: '/splash/app-2064x2752.png', media: 'screen and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 12.9
  { url: '/splash/app-2048x2732.png', media: 'screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11 (M4)
  { url: '/splash/app-1668x2420.png', media: 'screen and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11
  { url: '/splash/app-1668x2388.png', media: 'screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Air 4/5/11", iPad 10th/11th
  { url: '/splash/app-1640x2360.png', media: 'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 10.5 / Air 3
  { url: '/splash/app-1668x2224.png', media: 'screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad 7/8/9 (10.2")
  { url: '/splash/app-1620x2160.png', media: 'screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad 9.7 / mini 5
  { url: '/splash/app-1536x2048.png', media: 'screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad mini 6/7
  { url: '/splash/app-1488x2266.png', media: 'screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
];
