// The Biology definitions list (3 Oct 2026) — the same page as the Physics one
// (lib/science-definitions.ts), by O-Level Biology (6093) topic. **bold** = the
// words a marking point wants. Pure data; the parser and search are shared.
import { defn as d, type Definition } from './science-definitions';

export const BIOLOGY_TOPICS: readonly string[] = [
  'Cells', 'Movement of substances', 'Biological molecules', 'Enzymes', 'Nutrition in humans',
  'Transport in humans', 'Respiration', 'Excretion', 'Homeostasis', 'Nervous system and hormones',
  'Infectious diseases', 'Nutrition in plants', 'Transport in plants', 'Ecology',
  'Molecular genetics', 'Reproduction', 'Inheritance',
];

export const BIOLOGY_DEFINITIONS: readonly Definition[] = [
  d('Cells', 'Cell membrane', 'A **partially permeable** membrane that **controls the movement of substances** into and out of the cell.'),
  d('Cells', 'Cell wall', 'A **fully permeable** layer of **cellulose** that **protects** the plant cell and gives it a **fixed shape**.'),
  d('Cells', 'Nucleus', '**Controls cell activities** such as cell division, and contains the **genetic material (DNA)**.'),
  d('Cells', 'Mitochondrion', 'The site of **aerobic respiration**, where **energy is released** for cell activities.'),
  d('Cells', 'Chloroplast', 'Contains **chlorophyll**, which **absorbs light energy** for **photosynthesis**.'),
  d('Cells', 'Ribosome', 'The site of **protein synthesis**.'),
  d('Cells', 'Differentiation', 'The process by which a cell becomes **specialised for a specific function**.'),
  d('Cells', 'Tissue', 'A group of **similar cells** working together to perform a **specific function**.'),
  d('Cells', 'Organ', '**Different tissues** working together to perform a **specific function**.'),

  d('Movement of substances', 'Diffusion', 'The **net movement of particles** from a region of **higher concentration** to a region of **lower concentration**, **down a concentration gradient**.'),
  d('Movement of substances', 'Osmosis', 'The **net movement of water molecules** from a region of **higher water potential** to a region of **lower water potential**, through a **partially permeable membrane**.'),
  d('Movement of substances', 'Active transport', 'The movement of particles **against a concentration gradient**, from lower to higher concentration, using **energy from respiration**.'),
  d('Movement of substances', 'Water potential', 'A measure of the **tendency of water molecules to move** from one region to another. A **dilute** solution has a **higher** water potential.'),
  d('Movement of substances', 'Turgid', 'A plant cell that is **firm** because water has **entered by osmosis** and the vacuole **pushes against the cell wall**.'),
  d('Movement of substances', 'Plasmolysis', 'The **cytoplasm and cell membrane shrink away from the cell wall** when a plant cell **loses water by osmosis**.'),
  d('Movement of substances', 'Crenation', 'An animal cell **shrinks and forms spikes** when it **loses water by osmosis**.'),

  d('Biological molecules', 'Carbohydrate', 'An organic molecule made of **carbon, hydrogen and oxygen**, with hydrogen and oxygen in the ratio **2 : 1**.'),
  d('Biological molecules', 'Reducing sugar test', 'Add **Benedict’s solution** and **heat in a boiling water bath**. Blue solution gives a **green, yellow, orange or brick-red precipitate**.'),
  d('Biological molecules', 'Starch test', 'Add **iodine solution**. It turns from **brown to blue-black**.'),
  d('Biological molecules', 'Protein test', 'Add **biuret solution** (sodium hydroxide, then copper(II) sulfate). It turns from **blue to violet**.'),
  d('Biological molecules', 'Fat test', 'Add **ethanol** and shake, then add **water**. A **white emulsion** forms.'),

  d('Enzymes', 'Enzyme', 'A **protein** that acts as a **biological catalyst**: it **speeds up a chemical reaction** and **remains chemically unchanged** at the end.'),
  d('Enzymes', 'Active site', 'The part of the enzyme with a **specific three-dimensional shape**, **complementary** to the shape of its **substrate**.'),
  d('Enzymes', 'Lock and key hypothesis', 'The **substrate (key) fits into the active site** of the enzyme (lock) to form an **enzyme–substrate complex**; the products then leave.'),
  d('Enzymes', 'Activation energy', 'The **energy needed to start** a chemical reaction. An enzyme **lowers** it.'),
  d('Enzymes', 'Denaturation', 'The **loss of the three-dimensional shape of the active site**, so the **substrate no longer fits**. Caused by high temperature or extreme pH.'),
  d('Enzymes', 'Optimum temperature', 'The temperature at which the enzyme is **most active** and the **rate of reaction is highest**.'),

  d('Nutrition in humans', 'Digestion', 'The **breakdown of large, insoluble food molecules** into **small, soluble molecules** that can be **absorbed**.'),
  d('Nutrition in humans', 'Physical digestion', 'Breaking food into **smaller pieces** to **increase the surface area** for enzymes. **No new substances** are formed.'),
  d('Nutrition in humans', 'Chemical digestion', 'The breakdown of large molecules into small, soluble molecules by **enzymes**.'),
  d('Nutrition in humans', 'Peristalsis', '**Rhythmic, wave-like contractions** of the gut wall muscles that **push food along** the gut.'),
  d('Nutrition in humans', 'Absorption', 'The movement of **digested food molecules** through the wall of the **small intestine** into the **blood**.'),
  d('Nutrition in humans', 'Assimilation', 'The process by which absorbed food molecules are **used by cells** or **converted into new protoplasm**.'),
  d('Nutrition in humans', 'Emulsification', '**Bile** breaks **large fat droplets into small fat droplets**, **increasing the surface area** for lipase.'),
  d('Nutrition in humans', 'Deamination', 'The **removal of the amino group** from **excess amino acids** in the **liver**. The amino group is converted to **urea**.'),

  d('Transport in humans', 'Artery', 'A blood vessel that carries blood **away from the heart**, at **high pressure**. It has a **thick, muscular and elastic wall**.'),
  d('Transport in humans', 'Vein', 'A blood vessel that carries blood **towards the heart**, at **low pressure**. It has **valves** to **prevent backflow**.'),
  d('Transport in humans', 'Capillary', 'A blood vessel with a **wall one cell thick**, for the **exchange of substances** between blood and tissue cells.'),
  d('Transport in humans', 'Double circulation', 'Blood passes through the **heart twice** in **one complete circuit** of the body.'),
  d('Transport in humans', 'Coronary heart disease', '**Fatty deposits** build up in the **coronary arteries** and **narrow the lumen**, so **less oxygen and glucose** reach the heart muscle.'),
  d('Transport in humans', 'Phagocytosis', 'A white blood cell (phagocyte) **engulfs and digests** foreign particles such as bacteria.'),
  d('Transport in humans', 'Tissue fluid', 'The fluid that **surrounds tissue cells**. It carries dissolved substances **between the blood capillaries and the cells**.'),

  d('Respiration', 'Aerobic respiration', 'The **breakdown of glucose in the presence of oxygen**, releasing a **large amount of energy**, with **carbon dioxide and water** as products.', 'glucose + oxygen → carbon dioxide + water'),
  d('Respiration', 'Anaerobic respiration', 'The **breakdown of glucose in the absence of oxygen**, releasing a **small amount of energy**.', 'in muscle: glucose → lactic acid'),
  d('Respiration', 'Oxygen debt', 'The **amount of oxygen needed to remove the lactic acid** built up in the muscles during vigorous exercise.'),
  d('Respiration', 'Gas exchange', 'The **diffusion** of **oxygen into the blood** and **carbon dioxide out of the blood** across the wall of the **alveolus**.'),

  d('Excretion', 'Excretion', 'The **removal of metabolic waste products**, toxic substances and substances in excess from the body.'),
  d('Excretion', 'Ultrafiltration', '**High blood pressure** in the **glomerulus** forces **small molecules** (water, glucose, salts, urea) out of the blood into the **Bowman’s capsule**.'),
  d('Excretion', 'Selective reabsorption', '**Useful substances** (all the glucose, most of the water and salts) are **taken back into the blood** from the kidney tubule.'),
  d('Excretion', 'Dialysis', 'A machine removes **urea and excess salts** from the blood by **diffusion** across a **partially permeable** tubing.'),

  d('Homeostasis', 'Homeostasis', 'The **maintenance of a constant internal environment**.'),
  d('Homeostasis', 'Negative feedback', 'A **change from the normal** condition is detected and brings about the **opposite effect**, so the condition **returns to normal**.'),
  d('Homeostasis', 'Vasodilation', 'The **arterioles** near the skin surface **widen**, so **more blood** flows to the skin capillaries and **more heat is lost**.'),
  d('Homeostasis', 'Vasoconstriction', 'The **arterioles** near the skin surface **narrow**, so **less blood** flows to the skin capillaries and **less heat is lost**.'),

  d('Nervous system and hormones', 'Hormone', 'A **chemical substance** produced in small amounts by an **endocrine gland**, **carried in the blood** to **target organs**, where it has its effect.'),
  d('Nervous system and hormones', 'Reflex action', 'An **immediate response** to a stimulus **without conscious control**.'),
  d('Nervous system and hormones', 'Reflex arc', 'The **shortest pathway** of a nerve impulse from the **receptor to the effector**.'),
  d('Nervous system and hormones', 'Synapse', 'The **junction between two neurones**. The impulse crosses it as a **chemical**.'),
  d('Nervous system and hormones', 'Receptor', 'A cell or organ that **detects a stimulus** and produces **nerve impulses**.'),
  d('Nervous system and hormones', 'Effector', 'A **muscle or gland** that **carries out the response**.'),
  d('Nervous system and hormones', 'Insulin', 'A hormone from the **pancreas** (islets of Langerhans) that **lowers blood glucose concentration**: the liver converts **glucose to glycogen**.'),
  d('Nervous system and hormones', 'Glucagon', 'A hormone from the **pancreas** that **raises blood glucose concentration**: the liver converts **glycogen to glucose**.'),
  d('Nervous system and hormones', 'Diabetes mellitus', 'The body **cannot control its blood glucose concentration**, because it does not produce enough **insulin** or does not respond to it.'),

  d('Infectious diseases', 'Infectious disease', 'A disease caused by a **pathogen** that can be **spread from one person to another**.'),
  d('Infectious diseases', 'Pathogen', 'An organism that **causes disease**, such as a bacterium or a virus.'),
  d('Infectious diseases', 'Vaccine', 'Contains an agent that **resembles a pathogen**. It stimulates white blood cells to produce **antibodies**, so the body responds **quickly** to a later infection.'),
  d('Infectious diseases', 'Antibiotic', 'A drug that **kills bacteria or stops their growth**. It has **no effect on viruses**.'),
  d('Infectious diseases', 'Antibiotic resistance', 'Bacteria that **survive an antibiotic** reproduce and **pass on the resistance**. Caused by misuse and overuse of antibiotics.'),

  d('Nutrition in plants', 'Photosynthesis', 'The process in which **light energy** absorbed by **chlorophyll** is converted into **chemical energy**, used to make **glucose** from **carbon dioxide and water**. **Oxygen** is released.', 'carbon dioxide + water → glucose + oxygen'),
  d('Nutrition in plants', 'Limiting factor', 'The factor that **directly affects the rate** of a process when its amount is changed.'),
  d('Nutrition in plants', 'Stoma', 'A **pore** in the leaf epidermis, between two **guard cells**, for **gas exchange**.'),

  d('Transport in plants', 'Xylem', 'Transports **water and mineral salts** from the roots to the leaves, and gives **mechanical support**.'),
  d('Transport in plants', 'Phloem', 'Transports **sucrose and amino acids** from the leaves to the other parts of the plant.'),
  d('Transport in plants', 'Transpiration', 'The **loss of water vapour** from the aerial parts of the plant, mainly through the **stomata** of the leaves.'),
  d('Transport in plants', 'Transpiration pull', 'The **suction force** caused by transpiration that **pulls water up the xylem**.'),
  d('Transport in plants', 'Translocation', 'The transport of **sucrose and amino acids** in the **phloem**.'),
  d('Transport in plants', 'Wilting', 'Cells lose their **turgor** and become **flaccid** when the **rate of water loss exceeds the rate of water absorption**.'),

  d('Ecology', 'Habitat', 'The **place where an organism lives**.'),
  d('Ecology', 'Population', 'A group of organisms of the **same species** living in the **same habitat**.'),
  d('Ecology', 'Community', '**All the populations** of different species living in the same habitat.'),
  d('Ecology', 'Ecosystem', 'A **community** of organisms **interacting with one another and with their physical environment**.'),
  d('Ecology', 'Producer', 'An organism that **makes its own food** by **photosynthesis**.'),
  d('Ecology', 'Consumer', 'An organism that **obtains energy by feeding on other organisms**.'),
  d('Ecology', 'Decomposer', 'An organism that **breaks down dead organisms and waste**, returning nutrients to the environment.'),
  d('Ecology', 'Food chain', 'A series of organisms through which **energy is transferred** in the form of food.'),
  d('Ecology', 'Trophic level', 'The **feeding position** of an organism in a food chain.'),
  d('Ecology', 'Carbon sink', 'An area that **stores more carbon than it releases**, such as a forest or an ocean.'),
  d('Ecology', 'Eutrophication', '**Excess nitrates and phosphates** cause **rapid growth of algae**; when the algae die, **bacteria decompose** them and **use up the dissolved oxygen**, so aquatic organisms die.'),
  d('Ecology', 'Bioaccumulation', 'A substance that **cannot be broken down or excreted** builds up **in the body of an organism**.'),
  d('Ecology', 'Biodiversity', 'The **range of species** living in an ecosystem.'),

  d('Molecular genetics', 'Gene', 'A **sequence of nucleotides** on a DNA molecule that **controls the production of one polypeptide**.'),
  d('Molecular genetics', 'Complementary base pairing', '**Adenine pairs with thymine** and **guanine pairs with cytosine**.'),
  d('Molecular genetics', 'Transcription', 'The **base sequence of a gene is copied** into a molecule of **mRNA**, in the **nucleus**.'),
  d('Molecular genetics', 'Translation', 'The **mRNA** is used at a **ribosome** to join **amino acids** in the correct order to make a **polypeptide**.'),
  d('Molecular genetics', 'Genetic engineering', 'The **transfer of a gene** from one organism to another, so that the gene is **expressed** in the organism that receives it.'),

  d('Reproduction', 'Asexual reproduction', 'The production of **genetically identical** offspring from **one parent**, **without the fusion of gametes**.'),
  d('Reproduction', 'Sexual reproduction', 'The **fusion of two gametes** to form a **zygote**, producing **genetically different** offspring.'),
  d('Reproduction', 'Mitosis', 'Nuclear division that produces **two daughter nuclei genetically identical** to the parent nucleus, with the **same number of chromosomes**.'),
  d('Reproduction', 'Meiosis', 'Nuclear division that produces **four daughter nuclei**, each with **half the number of chromosomes**, **genetically different** from one another.'),
  d('Reproduction', 'Fertilisation', 'The **fusion of the nucleus** of a male gamete with the nucleus of a female gamete to form a **zygote**.'),
  d('Reproduction', 'Pollination', 'The **transfer of pollen grains** from the **anther to the stigma**.'),
  d('Reproduction', 'Diploid', 'A nucleus with **two sets of chromosomes**, written 2n.'),
  d('Reproduction', 'Haploid', 'A nucleus with **one set of chromosomes**, written n.'),
  d('Reproduction', 'Implantation', 'The **embryo embeds itself** in the **uterine lining**.'),

  d('Inheritance', 'Allele', 'One of the **different forms of a gene**. Alleles occupy the **same position** on a pair of homologous chromosomes.'),
  d('Inheritance', 'Genotype', 'The **genetic make-up** of an organism: the **combination of alleles** it has.'),
  d('Inheritance', 'Phenotype', 'The **expressed trait** of an organism, the result of its genotype and the environment.'),
  d('Inheritance', 'Dominant allele', 'An allele that **expresses itself** in **both the homozygous and the heterozygous** condition.'),
  d('Inheritance', 'Recessive allele', 'An allele that **expresses itself only in the homozygous** condition.'),
  d('Inheritance', 'Homozygous', 'Having **two identical alleles** of a gene.'),
  d('Inheritance', 'Heterozygous', 'Having **two different alleles** of a gene.'),
  d('Inheritance', 'Co-dominance', '**Both alleles are expressed** in the phenotype of a heterozygous organism.'),
  d('Inheritance', 'Mutation', 'A **sudden, random change** in the **structure of a gene** or in the **number of chromosomes**.'),
  d('Inheritance', 'Continuous variation', 'A **range of phenotypes** with no clear categories, controlled by **many genes** and **affected by the environment**. Example: height.'),
  d('Inheritance', 'Discontinuous variation', '**A few clear-cut phenotypes**, controlled by **one or a few genes** and **not affected by the environment**. Example: blood group.'),
  d('Inheritance', 'Natural selection', 'Organisms with **favourable traits survive, reproduce** and **pass on their alleles** to their offspring.'),
];
