import type { Metadata } from 'next';

// PWA metadata for the marking page, with its OWN icon (3 Sep 2026, Adrian:
// "a better icon for web app for mark paper" — it shared the hub's navy "A"
// with two other tiles on his home screen). Icon = the marking pen's red tick
// on a cream sheet, generated by scripts/generate-icons.js (`pictorial`).
export const metadata: Metadata = {
  title: "Mark Paper — Adrian's Math Tuition",
  manifest: '/manifest-mark-paper.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Mark Paper',
  },
  icons: {
    apple: '/icons/mark-paper-180.png',
  },
};

export default function MarkPaperLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
