#!/usr/bin/env node
// Inject link-preview (Open Graph) tags into the static tool pages.
//
// public/tools/*.html are plain files served byte-for-byte — they are NOT Next routes,
// so they cannot use src/lib/og.ts. This writes the equivalent tags straight into each
// <head>, sourcing titles/descriptions from the TOOLS array in src/app/tools/page.tsx
// so the cards and the /tools listing can never drift apart.
//
// Idempotent: the block is fenced by markers and replaced wholesale on re-run.
// Run after editing a tool's title/desc:  node scripts/og-tools.mjs

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://adrianmathtuition.com';
const START = '<!-- og:start — generated by scripts/og-tools.mjs, do not hand-edit -->';
const END = '<!-- og:end -->';

const decode = (s) =>
  s
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(+n))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');

const attr = (s) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

// The card subline wants one punchy sentence, not the whole listing blurb.
// Only pull in a second sentence if the first is short AND both still fit — otherwise
// the cap chops mid-word, which looks like a bug on the card.
// A complete first sentence is always worth keeping whole (HARD), even when it runs a
// little past the length we'd accept before pulling in a second sentence (CAP).
const CAP = 120;
const HARD = 145;

function subline(desc) {
  const parts = (desc.match(/[^.?!]+[.?!]/g) ?? [desc]).map((s) => s.trim());
  let out = parts[0];
  if (out.length < 45 && parts[1] && out.length + parts[1].length + 1 <= CAP) {
    out += ' ' + parts[1];
  }
  if (out.length <= HARD) return out;
  const cut = out.slice(0, HARD);
  const sp = cut.lastIndexOf(' ');
  return (sp > 60 ? cut.slice(0, sp) : cut).replace(/[,;:—–-]$/, '').trimEnd() + '…';
}

const listing = readFileSync(join(ROOT, 'src/app/tools/page.tsx'), 'utf8');
const TOOLS = [
  ...listing.matchAll(
    /\{\s*slug:\s*'([^']+)',\s*icon:\s*'[^']*',\s*title:\s*'([^']+)',\s*\n?\s*desc:\s*'([^']+)'\s*\}/g,
  ),
].map(([, slug, title, desc]) => ({ slug, title, desc }));

if (TOOLS.length === 0) {
  console.error('[og-tools] parsed 0 tools from src/app/tools/page.tsx — aborting');
  process.exit(1);
}

let written = 0;
const missing = [];

for (const { slug, title, desc } of TOOLS) {
  const file = join(ROOT, 'public/tools', `${slug}.html`);
  if (!existsSync(file)) {
    missing.push(slug);
    continue;
  }

  let html = readFileSync(file, 'utf8');
  html = html.replace(new RegExp(`\\n?${START}[\\s\\S]*?${END}`), '');

  const pageTitle = decode((html.match(/<title>([\s\S]*?)<\/title>/i) ?? [, title])[1].trim());
  const url = `${ORIGIN}/tools/${slug}.html`;
  const img =
    `${ORIGIN}/api/og?title=${encodeURIComponent(title)}` +
    `&sub=${encodeURIComponent(subline(desc))}&tag=${encodeURIComponent('Interactive tool')}`;

  const block = [
    START,
    `<meta name="description" content="${attr(desc)}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="Adrian&apos;s Math Tuition">`,
    `<meta property="og:locale" content="en_SG">`,
    `<meta property="og:url" content="${attr(url)}">`,
    `<meta property="og:title" content="${attr(pageTitle)}">`,
    `<meta property="og:description" content="${attr(desc)}">`,
    `<meta property="og:image" content="${attr(img)}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<link rel="canonical" href="${attr(url)}">`,
    END,
  ].join('\n');

  // Anchor to the viewport meta — present in every tool page, always inside <head>.
  const anchor = html.match(/<meta name="viewport"[^>]*>/i);
  if (!anchor) {
    missing.push(`${slug} (no viewport meta)`);
    continue;
  }
  html = html.replace(anchor[0], `${anchor[0]}\n${block}`);

  writeFileSync(file, html);
  written++;
}

console.log(`[og-tools] ✅ ${written}/${TOOLS.length} tool pages tagged`);
if (missing.length) console.log(`[og-tools] ⚠ skipped: ${missing.join(', ')}`);
